### ISSUE TITLE
Use InvariantCulture

### ISSUE THREAD

**Issue by xiaoxiao921** [ArcPh1r3/HenryTutorial#3]
Depending on the user region the behavior of methods like ToLower can be different. 
Which can cause issues and if check to fail for some users with different langages and will succeed for others.
https://github.com/ArcPh1r3/HenryTutorial/blob/master/HenryMod/Modules/Assets.cs#L215

The solution is to the Invariant varations of those methods instead
<https://docs.microsoft.com/en-us/dotnet/api/system.string.tolowerinvariant?view=net-5.0>

**Comment by MythicManiac** [comment]
Just adding to this, the current use (`ToLower()` instead of `ToLowerInvariant()`) is causing issues that I've seen user reports about, where users have had to change their system locale to get things working properly. In otherwords this isn't merely an improvement suggestion, but an actual bug report.

**Comment by TheTimeSweeper** [comment]
fixed 👍
