### ISSUE TITLE
Primary skill attack does not hit enemies in range

### ISSUE THREAD

**Issue by ethanrweber** [ArcPh1r3/HenryTutorial#6]
The primary skill slash attack does not hit enemies. The sword animation just swings through them, but the enemies are not attacked by it.
Tested using the current master branch and on game version 2019.4.26.14636 with the SotV dlc

**Comment by TheTimeSweeper** [comment]
more-or-less intentional. 
https://github.com/ArcPh1r3/HenryTutorial/blob/a5a9cf67a80f9f862eb3c75ba19cc3f8b22c199d/HenryMod/Content/MyCharacter.cs#L77-L85
The hitbox code is commented out, as someone's new character model wouldn't have the same hitboxes as henry, erroring on import. Un-comment this and henry's hitbox will work again
